group 'com.github.cloudwebrtc.flutter_callkeep'
version '1.0'

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 35
    namespace 'com.github.cloudwebrtc.flutter_callkeep'

    defaultConfig {
        minSdkVersion 21
    }
    lintOptions {
        disable 'InvalidPackage'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
    implementation 'androidx.annotation:annotation:1.8.2'
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
}
